### ISSUE TITLE
HOME/QSN/CONTATO/MATÉRIAS

### ISSUE THREAD

**Issue by bettercallvithor** [shaunkeyd/APS#3]
Centralizar os botões HOME/QSN/CONTATO/MATÉRIAS, não to fazendo ideia de como arrumar isso.

**Comment by pastega** [comment]
@otinti Esses botões estão em um cotainer flex, junto com a logo e a marca Agricoule Unip. Dá pra usar um justify-content: center no container. Mas eu acho que no mobile não ia ficar legal

**Comment by bettercallvithor** [comment]
@pastega Removi o justify-content, e acabou funcionando, espero que não atrapalhe na adição de mais alguma coisa, mas o problema resolveu.
